on:
  push:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
      - name: Use Node.js v20
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: "20.x"
      - name: use pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10.6.5

      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - name: restore node_modules
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: node_modules
          key: node-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: restore next.js build cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          key: next
          path: .next/cache

      - name: npm install
        run: |
          pnpm install --frozen-lockfile
      - name: build storybook
        run: |
          pnpm build-storybook
      - name: screenshot
        run: |
          pnpm run:storycap
      - name: run reg-suit
        env:
          # --- 認証情報 ---
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}

          # --- R2/S3プラグイン設定 (🔴 ここを修正) ---
          REG_PUBLISH_S3_PLUGIN_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          AWS_ENDPOINT_URL: ${{ secrets.REG_SUIT_ENDPOINT }} # AWS SDK v3 はこの変数を参照する

          # --- GitHub通知プラグイン設定 ---
          REG_SUIT_CLIENT_ID: ${{ secrets.REG_SUIT_CLIENT_ID }}
        run: |
          pnpm reg-suit run
